name: Build and Push to DO Registry 🚀
run-name: Build and Push to DO Registry 🚀

on:
  workflow_call:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            K8S_CLUSTER_NAME: rapt-k8-cluster
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install doctl
                uses: digitalocean/action-doctl@v2
                with:
                    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            -   name: Login to DO Registry with Short-lived credentials
                run: doctl registry login --expiry-seconds 1200
      
            -   name: Build rapt_service image
                run: |
                    docker build \
                        -t registry.digitalocean.com/rapt-container-registry/rapt_service:latest \
                        -t registry.digitalocean.com/rapt-container-registry/rapt_service:${GITHUB_SHA::7} \
                        service/
      
            -   name: Build rapt_server image
                run: |
                    docker build \
                        -t registry.digitalocean.com/rapt-container-registry/rapt_server:latest \
                        -t registry.digitalocean.com/rapt-container-registry/rapt_server:${GITHUB_SHA::7} \
                        nginx/
      
            -   name: Push Images
                run: | 
                    docker push registry.digitalocean.com/rapt-container-registry/rapt_service --all-tags
                    docker push registry.digitalocean.com/rapt-container-registry/rapt_server --all-tags

      