name: Test, Build, and Deploy Rapt Chat App 🚀
run-name: Test, Build, and Deploy Rapt Chat App 🚀

on:
    workflow_call:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test_service:
        uses: PeterKahenya/rapt/.github/workflows/test.yml@main
    build_images:
        uses: PeterKahenya/rapt/.github/workflows/build.yml@main
        needs: test_service
    deploy_to_k8s:
        uses: PeterKahenya/rapt/.github/workflows/deploy.yml@main
        needs: build_images
