name: Deploy Rapt Chat App
run-name: Deploy to K8s Cluster 🚀

on:
    workflow_call:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            K8S_CLUSTER_NAME: rapt-k8-cluster
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install doctl
                uses: digitalocean/action-doctl@v2
                with:
                    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            -   name: Login to DO Registry with Short-lived credentials
                run: doctl registry login --expiry-seconds 1200
          
            -   name: K8s cluster kubeconfig file with Short-lived credentials
                run: |
                  doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.K8S_CLUSTER_NAME }}
        
            -   name: Update k8s secrets
                run: |
                  cat << EOF >> ./.env.prod
                  MYSQL_HOST=${{ secrets.MYSQL_HOST }}
                  MYSQL_PORT=${{ secrets.MYSQL_PORT }}
                  MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
                  MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
                  MYSQL_USER=${{ secrets.MYSQL_USER }}
                  MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
                  API_URL=${{ secrets.API_URL }}
                  EOF
        
                  kubectl delete secrets rapt-prod-env-secrets
                  kubectl create secret generic rapt-prod-env-secrets --from-env-file ./.env.prod
            
            -   name: Apply k8s manifests
                run: |
                  kubectl apply -f k8s/rapt_service.yml
                  kubectl apply -f k8s/rapt_server.yml

            -   name: Update Deployment Images
                run: |
                  kubectl set image deployment/rapt-service-deployment rapt-api=registry.digitalocean.com/rapt-container-registry/rapt_service:${GITHUB_SHA::7}
                  kubectl set image deployment/rapt-server-deployment rapt-server=registry.digitalocean.com/rapt-container-registry/rapt_server:${GITHUB_SHA::7}
        
            -   name: Wait for Rollout to finish
                run: |
                  kubectl rollout status deployment/rapt-api-deployment
                  kubectl rollout status deployment/rapt-server-deployment
                  